// Mocks generated by Mockito 5.4.2 from annotations
// in pedalpulse/test/mocks/database/mock_query_snapshot.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSnapshotMetadata_0 extends _i1.SmartFake
    implements _i2.SnapshotMetadata {
  _FakeSnapshotMetadata_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [QuerySnapshot].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuerySnapshot extends _i1.Mock
    implements _i2.QuerySnapshot<Map<String, dynamic>> {
  @override
  List<_i2.QueryDocumentSnapshot<Map<String, dynamic>>> get docs =>
      (super.noSuchMethod(
        Invocation.getter(#docs),
        returnValue: <_i2.QueryDocumentSnapshot<Map<String, dynamic>>>[],
        returnValueForMissingStub: <_i2
            .QueryDocumentSnapshot<Map<String, dynamic>>>[],
      ) as List<_i2.QueryDocumentSnapshot<Map<String, dynamic>>>);

  @override
  List<_i2.DocumentChange<Map<String, dynamic>>> get docChanges =>
      (super.noSuchMethod(
        Invocation.getter(#docChanges),
        returnValue: <_i2.DocumentChange<Map<String, dynamic>>>[],
        returnValueForMissingStub: <_i2.DocumentChange<Map<String, dynamic>>>[],
      ) as List<_i2.DocumentChange<Map<String, dynamic>>>);

  @override
  _i2.SnapshotMetadata get metadata => (super.noSuchMethod(
        Invocation.getter(#metadata),
        returnValue: _FakeSnapshotMetadata_0(
          this,
          Invocation.getter(#metadata),
        ),
        returnValueForMissingStub: _FakeSnapshotMetadata_0(
          this,
          Invocation.getter(#metadata),
        ),
      ) as _i2.SnapshotMetadata);

  @override
  int get size => (super.noSuchMethod(
        Invocation.getter(#size),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);
}
