// Mocks generated by Mockito 5.4.2 from annotations
// in pedalpulse/test/mocks/banners/mock_banners_datasource.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pedalpulse/features/banners/data/datasources/banners_datasource.dart'
    as _i3;
import 'package:pedalpulse/features/banners/domain/entities/banner_entity.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUnit_0 extends _i1.SmartFake implements _i2.Unit {
  _FakeUnit_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BannersDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBannersDataSource extends _i1.Mock implements _i3.BannersDataSource {
  @override
  _i4.Future<List<_i5.BannerEntity>> getBanners() => (super.noSuchMethod(
        Invocation.method(
          #getBanners,
          [],
        ),
        returnValue:
            _i4.Future<List<_i5.BannerEntity>>.value(<_i5.BannerEntity>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.BannerEntity>>.value(<_i5.BannerEntity>[]),
      ) as _i4.Future<List<_i5.BannerEntity>>);

  @override
  _i4.Future<_i2.Unit> increaseBannerViews({required String? uid}) =>
      (super.noSuchMethod(
        Invocation.method(
          #increaseBannerViews,
          [],
          {#uid: uid},
        ),
        returnValue: _i4.Future<_i2.Unit>.value(_FakeUnit_0(
          this,
          Invocation.method(
            #increaseBannerViews,
            [],
            {#uid: uid},
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.Unit>.value(_FakeUnit_0(
          this,
          Invocation.method(
            #increaseBannerViews,
            [],
            {#uid: uid},
          ),
        )),
      ) as _i4.Future<_i2.Unit>);
}
