// Mocks generated by Mockito 5.4.2 from annotations
// in pedalpulse/test/mocks/user/mock_user_entity.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:pedalpulse/features/user/domain/entities/user_entity.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserEntity].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserEntity extends _i1.Mock implements _i2.UserEntity {
  @override
  String get uid => (super.noSuchMethod(
        Invocation.getter(#uid),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);

  @override
  String get username => (super.noSuchMethod(
        Invocation.getter(#username),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);

  @override
  String get email => (super.noSuchMethod(
        Invocation.getter(#email),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);

  @override
  String get profileImage => (super.noSuchMethod(
        Invocation.getter(#profileImage),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);

  @override
  String get coverImage => (super.noSuchMethod(
        Invocation.getter(#coverImage),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);

  @override
  String get bio => (super.noSuchMethod(
        Invocation.getter(#bio),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);

  @override
  DateTime get joinedAt => (super.noSuchMethod(
        Invocation.getter(#joinedAt),
        returnValue: _FakeDateTime_0(
          this,
          Invocation.getter(#joinedAt),
        ),
        returnValueForMissingStub: _FakeDateTime_0(
          this,
          Invocation.getter(#joinedAt),
        ),
      ) as DateTime);
}
