// Mocks generated by Mockito 5.4.2 from annotations
// in pedalpulse/test/mocks/user/mock_user_datasource.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_image_compress/flutter_image_compress.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pedalpulse/features/user/data/datasources/user_datasource.dart'
    as _i3;
import 'package:pedalpulse/features/user/domain/entities/user_entity.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserEntity_0 extends _i1.SmartFake implements _i2.UserEntity {
  _FakeUserEntity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserDataSource extends _i1.Mock implements _i3.UserDataSource {
  @override
  _i4.Future<_i2.UserEntity> getUser({required String? uid}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [],
          {#uid: uid},
        ),
        returnValue: _i4.Future<_i2.UserEntity>.value(_FakeUserEntity_0(
          this,
          Invocation.method(
            #getUser,
            [],
            {#uid: uid},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.UserEntity>.value(_FakeUserEntity_0(
          this,
          Invocation.method(
            #getUser,
            [],
            {#uid: uid},
          ),
        )),
      ) as _i4.Future<_i2.UserEntity>);

  @override
  _i4.Future<_i2.UserEntity> updateUser(
          {required _i2.UserEntity? userEntity}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [],
          {#userEntity: userEntity},
        ),
        returnValue: _i4.Future<_i2.UserEntity>.value(_FakeUserEntity_0(
          this,
          Invocation.method(
            #updateUser,
            [],
            {#userEntity: userEntity},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.UserEntity>.value(_FakeUserEntity_0(
          this,
          Invocation.method(
            #updateUser,
            [],
            {#userEntity: userEntity},
          ),
        )),
      ) as _i4.Future<_i2.UserEntity>);

  @override
  _i4.Future<List<String>> getUserLikes({required String? userUid}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserLikes,
          [],
          {#userUid: userUid},
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
        returnValueForMissingStub: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<void> addUserLike({
    required String? userUid,
    required String? postUid,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addUserLike,
          [],
          {
            #userUid: userUid,
            #postUid: postUid,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removeUserLike({
    required String? userUid,
    required String? postUid,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeUserLike,
          [],
          {
            #userUid: userUid,
            #postUid: postUid,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteUser({required String? uid}) => (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [],
          {#uid: uid},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateUserProfileImage({
    required String? uid,
    _i5.XFile? profileImage,
    _i5.XFile? coverImage,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserProfileImage,
          [],
          {
            #uid: uid,
            #profileImage: profileImage,
            #coverImage: coverImage,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
