// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnLCG8V3m_FWpN9pQ_r8rAQ2lop-Jpu5s',
    appId: '1:596570629532:web:64c8e909e07b185841d459',
    messagingSenderId: '596570629532',
    projectId: 'pedalpulse-1995d',
    authDomain: 'pedalpulse-1995d.firebaseapp.com',
    storageBucket: 'pedalpulse-1995d.appspot.com',
    measurementId: 'G-K15DDE52MH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq4NE5N8DG0_wY57K2aTXD2IZeP7STrWo',
    appId: '1:596570629532:android:6e4567bd30675e5141d459',
    messagingSenderId: '596570629532',
    projectId: 'pedalpulse-1995d',
    storageBucket: 'pedalpulse-1995d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGo-8Wf1cZrvLxofw_6sjyB1MFw2p9oic',
    appId: '1:596570629532:ios:ef01c19c2885b01c41d459',
    messagingSenderId: '596570629532',
    projectId: 'pedalpulse-1995d',
    storageBucket: 'pedalpulse-1995d.appspot.com',
    iosClientId: '596570629532-931obtr2acisgf86bkioaaaeehgmv5oi.apps.googleusercontent.com',
    iosBundleId: 'com.example.pedalpulse',
  );
}
