// Mocks generated by Mockito 5.4.2 from annotations
// in pedalpulse/test/mocks/auth/social/mock_google_auth_provider.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:firebase_auth_platform_interface/firebase_auth_platform_interface.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGoogleAuthProvider_0 extends _i1.SmartFake
    implements _i2.GoogleAuthProvider {
  _FakeGoogleAuthProvider_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GoogleAuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleAuthProvider extends _i1.Mock
    implements _i2.GoogleAuthProvider {
  @override
  List<String> get scopes => (super.noSuchMethod(
        Invocation.getter(#scopes),
        returnValue: <String>[],
        returnValueForMissingStub: <String>[],
      ) as List<String>);

  @override
  Map<dynamic, dynamic> get parameters => (super.noSuchMethod(
        Invocation.getter(#parameters),
        returnValue: <dynamic, dynamic>{},
        returnValueForMissingStub: <dynamic, dynamic>{},
      ) as Map<dynamic, dynamic>);

  @override
  String get providerId => (super.noSuchMethod(
        Invocation.getter(#providerId),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);

  @override
  _i2.GoogleAuthProvider addScope(String? scope) => (super.noSuchMethod(
        Invocation.method(
          #addScope,
          [scope],
        ),
        returnValue: _FakeGoogleAuthProvider_0(
          this,
          Invocation.method(
            #addScope,
            [scope],
          ),
        ),
        returnValueForMissingStub: _FakeGoogleAuthProvider_0(
          this,
          Invocation.method(
            #addScope,
            [scope],
          ),
        ),
      ) as _i2.GoogleAuthProvider);

  @override
  _i2.GoogleAuthProvider setCustomParameters(
          Map<dynamic, dynamic>? customOAuthParameters) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCustomParameters,
          [customOAuthParameters],
        ),
        returnValue: _FakeGoogleAuthProvider_0(
          this,
          Invocation.method(
            #setCustomParameters,
            [customOAuthParameters],
          ),
        ),
        returnValueForMissingStub: _FakeGoogleAuthProvider_0(
          this,
          Invocation.method(
            #setCustomParameters,
            [customOAuthParameters],
          ),
        ),
      ) as _i2.GoogleAuthProvider);
}
